-- Pavilion-AI Agentic CMS Database Initialization Script
-- Run this after creating Cloud SQL instance

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Grant permissions to pavilion_user
GRANT CONNECT ON DATABASE pavilion_agentic TO pavilion_user;
GRANT USAGE ON SCHEMA public TO pavilion_user;
GRANT CREATE ON SCHEMA public TO pavilion_user;

-- Tables for content embeddings (Phase 1)
CREATE TABLE IF NOT EXISTS cms_contentembedding (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    article_id INTEGER NOT NULL,
    embedding_vector BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(article_id)
);

CREATE INDEX idx_contentembedding_article_id ON cms_contentembedding(article_id);
CREATE INDEX idx_contentembedding_created_at ON cms_contentembedding(created_at);

-- Table for tracking semantic searches
CREATE TABLE IF NOT EXISTS cms_semanticsearch (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    query TEXT NOT NULL,
    results_count INTEGER,
    execution_time_ms FLOAT,
    user_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_semanticsearch_created_at ON cms_semanticsearch(created_at);
CREATE INDEX idx_semanticsearch_user_id ON cms_semanticsearch(user_id);

-- Extend Article model with embedding fields
-- (These will be added via Django migration, but documenting here)
-- ALTER TABLE cms_article ADD COLUMN IF NOT EXISTS embedding_id UUID REFERENCES cms_contentembedding(id);
-- ALTER TABLE cms_article ADD COLUMN IF NOT EXISTS embedding_generated_at TIMESTAMP WITH TIME ZONE;
-- ALTER TABLE cms_article ADD COLUMN IF NOT EXISTS version_number INTEGER DEFAULT 1;

-- Tables for Analytics (Phase 4)
CREATE TABLE IF NOT EXISTS analytics_contentperformance (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content_id INTEGER NOT NULL,
    content_version_id INTEGER,
    metric_date DATE NOT NULL,
    pageviews INTEGER DEFAULT 0,
    sessions INTEGER DEFAULT 0,
    user_engagement_duration_seconds FLOAT DEFAULT 0,
    bounce_rate FLOAT DEFAULT 0,
    avg_session_duration_seconds FLOAT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(content_id, content_version_id, metric_date)
);

CREATE INDEX idx_contentperformance_content_id ON analytics_contentperformance(content_id);
CREATE INDEX idx_contentperformance_metric_date ON analytics_contentperformance(metric_date);

-- Tables for Agent Workflows (Phase 3 - HITL)
CREATE TABLE IF NOT EXISTS cms_agentworkflow (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    article_id INTEGER NOT NULL,
    workflow_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    state JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_agentworkflow_article_id ON cms_agentworkflow(article_id);
CREATE INDEX idx_agentworkflow_status ON cms_agentworkflow(status);
CREATE INDEX idx_agentworkflow_created_at ON cms_agentworkflow(created_at);

-- Grants for all tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pavilion_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pavilion_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO pavilion_user;

-- Audit table
CREATE TABLE IF NOT EXISTS cms_auditlog (
    id BIGSERIAL PRIMARY KEY,
    workflow_id UUID,
    event_type VARCHAR(100) NOT NULL,
    event_details JSONB,
    user_id INTEGER,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_auditlog_workflow_id ON cms_auditlog(workflow_id);
CREATE INDEX idx_auditlog_timestamp ON cms_auditlog(timestamp);
CREATE INDEX idx_auditlog_event_type ON cms_auditlog(event_type);

-- Grant audit table permissions
GRANT SELECT, INSERT ON cms_auditlog TO pavilion_user;

-- Constraints and comments
COMMENT ON TABLE cms_contentembedding IS 'Stores vector embeddings for articles generated by Vertex AI';
COMMENT ON TABLE cms_semanticsearch IS 'Logs semantic search queries for analytics and optimization';
COMMENT ON TABLE analytics_contentperformance IS 'Performance metrics for article versions from GA4';
COMMENT ON TABLE cms_agentworkflow IS 'Tracks AI agent workflow execution for articles';
COMMENT ON TABLE cms_auditlog IS 'Complete audit trail of all actions';

-- Summary
-- This script creates the foundation tables for:
-- 1. Vector embeddings (Phase 1)
-- 2. Semantic search logging (Phase 1)
-- 3. Content performance metrics (Phase 4)
-- 4. Agent workflows (Phase 3)
-- 5. Audit logging (Phase 3)
--
-- Additional tables from Django migrations will be created automatically
-- via: python manage.py migrate
