# Generated by Django 5.2.7 on 2025-11-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_add_malayalam_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('reliable_sources', 'Reliable Sources'), ('trends', 'Trends'), ('subscriptions', 'Subscriptions')], default='reliable_sources', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='trend_data',
            field=models.JSONField(blank=True, help_text='Google Trends data', null=True),
        ),
    ]
