# Generated by Django 5.2.7 on 2025-11-06 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_article_category_category_article_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.ImageField(upload_to='media/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='cms_article_status_1ce983_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='cms_article_created_a655a4_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary_english',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='cms.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('reliable_sources', 'Reliable Sources'), ('trends', 'Trends'), ('subscriptions', 'Subscriptions')], default='reliable_sources', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='trend_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='cms_article_status_097409_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', '-created_at'], name='cms_article_categor_112636_idx'),
        ),
        migrations.AddField(
            model_name='media',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-created_at'], name='cms_media_created_76f297_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['uploaded_by'], name='cms_media_uploade_5c53a3_idx'),
        ),
    ]
