# Generated by Django 5.2.7 on 2025-11-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_media_remove_article_cms_article_status_1ce983_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='media',
            name='mime_type',
            field=models.CharField(default='image/jpeg', max_length=100),
        ),
    ]
