# Generated by Django 4.2.7 on 2025-12-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_add_audio_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='instagram_reel_audio',
            field=models.FileField(blank=True, help_text='Generated audio for Instagram Reel', null=True, upload_to='articles/reels/'),
        ),
        migrations.AddField(
            model_name='article',
            name='instagram_reel_script',
            field=models.TextField(blank=True, help_text='Script for Instagram Reel'),
        ),
    ]
