# Generated by Django 4.2.7 on 2025-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_article_instagram_reel_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='social_media_caption',
            field=models.TextField(blank=True, help_text='Engaging caption for social media post'),
        ),
        migrations.AddField(
            model_name='article',
            name='social_media_poster_text',
            field=models.TextField(blank=True, help_text='Short, punchy text for social media poster'),
        ),
    ]
