# Generated by Django 4.2.7 on 2026-01-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_article_social_media_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='templates/posters/')),
                ('text_config', models.JSONField(default=dict, help_text='JSON configuration for text placement')),
                ('image_config', models.JSONField(default=dict, help_text='JSON configuration for image placement')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='generated_poster',
            field=models.ImageField(blank=True, null=True, upload_to='articles/posters/'),
        ),
    ]
