# Generated by Django 4.2.7 on 2026-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_postertemplate_article_generated_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
