# Generated by Django 4.2.7 on 2026-01-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_article_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='poster_context',
            field=models.JSONField(blank=True, default=dict, help_text='JSON structure with poster details (text, stats, branding)'),
        ),
    ]
