# Generated by Django 4.2.7 on 2026-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_update_poster_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_cutout',
            field=models.ImageField(blank=True, help_text='Background-removed version of the featured image', null=True, upload_to='articles/cutouts/'),
        ),
    ]
