# Generated by Django 4.2.7 on 2026-01-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_article_featured_image_cutout'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Link to Media library item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_articles', to='cms.media'),
        ),
    ]
