# Generated by Django 4.2.7 on 2026-03-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('cms', '0016_article_featured_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='media',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webstory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webstories', to='tenants.tenant'),
        ),
    ]
