# Generated by Django 4.2.7 on 2026-03-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_article_tenant_category_tenant_media_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_audio_url',
            field=models.URLField(blank=True, help_text='Public URL of the narration audio (Vercel Blob)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video_format',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='video_script',
            field=models.TextField(blank=True, help_text='Script for the generated sports video'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('generating_script', 'Generating Script'), ('generating_video', 'Generating Video'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Status of the video generation pipeline', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='Public URL of the generated D-ID video (Vercel Blob)', max_length=500, null=True),
        ),
    ]
