# Generated by Django 4.2.7 on 2026-03-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_article_video_audio_url_article_video_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_error',
            field=models.TextField(blank=True, help_text='Error message if the video generation failed'),
        ),
    ]
