# Generated by Django 4.2.7 on 2026-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_article_video_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsroomx_dna',
            field=models.JSONField(blank=True, default=dict, help_text='Stored JSON DNA for the programmatic pipeline orchestration'),
        ),
        migrations.AddField(
            model_name='article',
            name='newsroomx_error',
            field=models.TextField(blank=True, help_text='Error message if the NewsroomX pipeline failed'),
        ),
        migrations.AddField(
            model_name='article',
            name='newsroomx_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('step_a_audio', 'Wait for Step A (Audio)'), ('step_b_avatar', 'Wait for Step B (Avatar)'), ('step_c_composition', 'Wait for Step C (Composition)'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=25),
        ),
        migrations.AddField(
            model_name='article',
            name='newsroomx_video_url',
            field=models.URLField(blank=True, help_text='Public URL of the final NewsroomX composition', max_length=1000, null=True),
        ),
    ]
