# Generated by Django 4.2.7 on 2026-04-22 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0020_article_newsroomx_dna_article_newsroomx_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task ID for the active background task', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Schedule future publishing at this datetime', null=True),
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cms.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='cms_article_article_671786_idx')],
            },
        ),
    ]
