# Generated by Django 4.2.7 on 2026-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_article_celery_task_id_publish_at_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_production_plan',
            field=models.JSONField(blank=True, default=dict, help_text='Complete AI-generated VideoProductionPlan JSON — includes scenes, clips, props, voiceover, assets'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('reliable_sources', 'Reliable Sources'), ('trends', 'Trends'), ('subscriptions', 'Subscriptions'), ('video_project', 'Video Project')], default='reliable_sources', max_length=50),
        ),
    ]
