# Generated by Django 4.2.7 on 2026-05-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_video_production_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reel_audio_url',
            field=models.URLField(blank=True, default='', help_text='TTS-generated Malayalam voiceover GCS URL', max_length=2000),
        ),
        migrations.AddField(
            model_name='article',
            name='reel_generation_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('running', 'Running'), ('review', 'Needs Review'), ('approved', 'Approved'), ('failed', 'Failed')], default='idle', help_text='Status of the new multi-agent reel pipeline', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='reel_pipeline_log',
            field=models.JSONField(blank=True, default=list, help_text='Per-agent execution log from the reel pipeline'),
        ),
        migrations.AddField(
            model_name='article',
            name='reel_video_url',
            field=models.URLField(blank=True, default='', help_text='Final rendered MP4 GCS URL written back by render task', max_length=2000),
        ),
    ]
