# Generated by Django 4.2.7 on 2026-05-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_userprofile_usagerecord'),
        ('cms', '0024_article_elevenlabs_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canva_export_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='social_post_celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='social_post_plan',
            field=models.JSONField(blank=True, default=dict, help_text='SocialPostCrew output keyed by template slot keys. Also carries _template_pk, _template_name, _canva_template_id.'),
        ),
        migrations.AddField(
            model_name='article',
            name='social_post_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.CreateModel(
            name='CanvaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('stat_comparison', 'Stat Comparison'), ('player_card', 'Player Card'), ('hero_headline', 'Hero Headline'), ('quote_card', 'Quote Card'), ('match_result', 'Match Result'), ('ticker', 'Ticker / Breaking')], default='hero_headline', max_length=30)),
                ('canva_template_id', models.CharField(blank=True, help_text='Canva template ID used in bulk-create uploads', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Plain-English description of the visual layout shown to the agent. E.g.: 'Two player cutouts side by side, headline at top, two stat boxes below, six bullet points, accent colour bar at bottom.'")),
                ('slots', models.JSONField(default=dict, help_text='Structured slot schema — see class docstring for full format.')),
                ('team_colors', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canva_templates', to='tenants.tenant')),
            ],
            options={
                'ordering': ['content_type', 'name'],
            },
        ),
    ]
