# Generated by Django 4.2.7 on 2026-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_canvatemplate_google_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvatemplate',
            name='content_type',
            field=models.CharField(choices=[('stat_comparison', 'Stat Comparison'), ('player_card', 'Player Card'), ('hero_headline', 'Hero Headline'), ('quote_card', 'Quote Card'), ('match_result', 'Match Result'), ('ticker', 'Ticker / Breaking'), ('predicted_xi', 'Predicted XI')], default='hero_headline', max_length=30),
        ),
        migrations.AlterField(
            model_name='canvatemplate',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='Google Sheet ID or full URL. Share the sheet with the GCP service account (Editor). Column headers must match slot key names.', max_length=255),
        ),
        migrations.AlterField(
            model_name='canvatemplate',
            name='sheet_tab_name',
            field=models.CharField(blank=True, default='Sheet1', help_text='Worksheet tab name (default: Sheet1)', max_length=100),
        ),
    ]
