# Generated by Django 4.2.7 on 2026-05-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_add_predicted_xi_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('fetched', 'Fetched'), ('generated', 'Generated'), ('review', 'Review'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='fetched', max_length=20),
        ),
    ]
