# Generated by Django 4.2.7 on 2026-06-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_social_post_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('CONFIRMED', 'Confirmed by multiple sources'), ('UNCONFIRMED', 'Single source or unverified'), ('CONTRADICTED', 'Contradicted — do not post'), ('PENDING', 'Check in progress')], default='PENDING', max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('sources', models.JSONField(default=list)),
                ('gemini_reasoning', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x_handle', models.CharField(max_length=100, unique=True)),
                ('credibility_tier', models.IntegerField(choices=[(1, 'Tier 1 - Top Sources'), (2, 'Tier 2 - Journalists'), (3, 'Tier 3 - Aggregators')], default=2)),
                ('category', models.CharField(choices=[('official', 'Official Account'), ('journalist', 'Journalist'), ('stats', 'Stats/Data'), ('federation', 'Federation'), ('aggregator', 'Aggregator')], default='journalist', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_tweet_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['credibility_tier', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='socialpostfeedback',
            new_name='cms_socialp_tenant__597fad_idx',
            old_name='cms_social_tenant_tmpl_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='source_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='traction_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='urgency',
            field=models.CharField(choices=[('breaking', 'Breaking'), ('standard', 'Standard'), ('low', 'Low Priority')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='canvatemplate',
            name='content_type',
            field=models.CharField(choices=[('stat_comparison', 'Stat Comparison'), ('player_card', 'Player Card'), ('hero_headline', 'Hero Headline'), ('quote_card', 'Quote Card'), ('match_result', 'Match Result'), ('ticker', 'Ticker / Breaking'), ('predicted_xi', 'Predicted XI'), ('fact_check', 'Fact Check'), ('playing_xi', 'Playing XI')], default='hero_headline', max_length=30),
        ),
        migrations.AddField(
            model_name='factcheck',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fact_check', to='cms.article'),
        ),
    ]
