# Generated by Django 4.2.7 on 2026-06-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_factcheck_socialmediahandle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canva_design_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='canva_export_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
