# Generated by Django 4.2.7 on 2026-06-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_article_engagement_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediahandle',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('instagram', 'Instagram')], default='twitter', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='x_handle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediahandle',
            unique_together={('x_handle', 'platform')},
        ),
    ]
