# Generated by Django 4.2.7 on 2026-06-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_userprofile_usagerecord'),
        ('cms', '0034_add_platform_to_socialmediahandle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('general', 'General')], default='general', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_handles', to='tenants.tenant')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('tenant', 'handle', 'category')},
            },
        ),
    ]
