# Generated by Django 4.2.7 on 2026-06-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_userprofile_usagerecord'),
        ('cms', '0035_feedhandle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedhandle',
            options={'ordering': ['position', 'added_at']},
        ),
        migrations.AddField(
            model_name='feedhandle',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FeedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_categories', to='tenants.tenant')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='feedhandle',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handles', to='cms.feedcategory'),
        ),
    ]
