# Generated by Django 4.2.7 on 2026-07-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_alter_feedhandle_options_feedhandle_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='generation_error',
            field=models.TextField(blank=True, default='', help_text='Human-readable reason the last AI generation failed (empty when healthy)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('fetched', 'Fetched'), ('generating', 'Generating'), ('generated', 'Generated'), ('review', 'Review'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('failed', 'Failed')], default='fetched', max_length=20),
        ),
    ]
