# Generated by Django 4.2.7 on 2026-05-02 07:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleDNA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this analysis', max_length=200)),
                ('source_url', models.URLField(help_text='Original reel/video URL that was analyzed')),
                ('analysis_json', models.JSONField(default=dict, help_text='Complete Style DNA output from the analyzer agent')),
                ('color_palette', models.JSONField(blank=True, default=dict)),
                ('animation_patterns', models.JSONField(blank=True, default=list)),
                ('scene_count', models.IntegerField(default=0)),
                ('layout_types', models.JSONField(blank=True, default=list, help_text="List of layout_type strings detected, e.g. ['hero_fullbleed', 'player_card_stats']")),
                ('analyzed_by_model', models.CharField(default='', help_text='Which AI model performed the analysis', max_length=100)),
                ('analysis_duration_seconds', models.FloatField(default=0)),
                ('analysis_cost_estimate_usd', models.FloatField(default=0, help_text='Estimated API cost for this analysis')),
                ('brand_compatibility_score', models.FloatField(default=0, help_text='0-1 score of how well this style fits Pavilion branding', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('adaptations_needed', models.JSONField(blank=True, default=list, help_text='List of changes needed to adapt this style to Pavilion brand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Style DNA Analysis',
                'verbose_name_plural': 'Style DNA Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable template name', max_length=200)),
                ('template_id', models.SlugField(help_text="Unique slug used in the pipeline, e.g. 'scoreboard_v1'", max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manually Created'), ('ai_generated', 'AI Generated'), ('ai_extracted', 'Extracted from Reference')], default='manual', max_length=20)),
                ('source_reference_url', models.URLField(blank=True, default='')),
                ('jsx_component', models.TextField(help_text='Full JSX source code for the Remotion Scene component')),
                ('description', models.TextField(help_text='What this scene looks like visually — fed to AI agents for matching')),
                ('required_props', models.JSONField(blank=True, default=list, help_text='List of prop keys that MUST be filled')),
                ('optional_props', models.JSONField(blank=True, default=list, help_text='List of prop keys with sensible defaults')),
                ('asset_slots', models.JSONField(blank=True, default=list, help_text='List of asset slot dicts {slot, type, description, required}')),
                ('suitable_for', models.JSONField(blank=True, default=list, help_text="Content types this template works well for, e.g. ['opening', 'stats']")),
                ('clips_definition', models.JSONField(blank=True, default=list, help_text='Clip definitions for timeline, same format as scene_templates_catalog clips')),
                ('duration_frames_default', models.IntegerField(default=180, help_text='Default duration in frames at 30fps', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1800)])),
                ('animation_presets', models.JSONField(blank=True, default=list, help_text='Animation patterns used by this template')),
                ('style_dna_snapshot', models.JSONField(blank=True, default=dict, help_text='Style DNA scene data that inspired this template')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('preview_video_url', models.URLField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False, help_text='True if this template passed a headless Remotion render test')),
                ('is_active', models.BooleanField(default=True, help_text='False = hidden from catalog but not deleted')),
                ('render_test_log', models.TextField(blank=True, default='', help_text='Output from the last render validation attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scene Template',
                'verbose_name_plural': 'Scene Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StylePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('template_sequence', models.JSONField(default=list, help_text='Ordered list of template assignments: [{template_id, duration_frames, props_override, animation_overrides}]')),
                ('brand_colors', models.JSONField(blank=True, default=dict, help_text='Override colors: {bgColor, cardColor, cardAccent, accent}')),
                ('animation_speed_multiplier', models.FloatField(default=1.0, help_text='Global speed modifier for all animations', validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(3.0)])),
                ('typography_overrides', models.JSONField(blank=True, default=dict, help_text='Font family/size overrides')),
                ('times_used', models.IntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_analysis', models.ForeignKey(blank=True, help_text='The Style DNA analysis that inspired this preset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='style_library.styledna')),
            ],
            options={
                'verbose_name': 'Style Preset',
                'verbose_name_plural': 'Style Presets',
                'ordering': ['-times_used', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='styledna',
            name='templates',
            field=models.ManyToManyField(blank=True, help_text='Templates that were created or matched from this analysis', related_name='source_analyses', to='style_library.styletemplate'),
        ),
    ]
