# Generated by Django 4.2.7 on 2026-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videojob',
            new_name='video_studi_tenant__71d9b1_idx',
            old_name='video_job_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='videojob',
            new_name='video_studi_tenant__8bbe12_idx',
            old_name='video_job_tenant_created_idx',
        ),
        migrations.AddField(
            model_name='videojob',
            name='clips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
