# Generated by Django 4.2.7 on 2026-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_fetcher', '0003_styleguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('general', 'General')], default='football', max_length=50),
        ),
    ]
